version: '3.4'

services: 
  jaeger: 
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  
  api-grpc-client:
      image: api-grpc-client:latest
      build: ./api-grpc-client
      ports:
        - "5001:80"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
        - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
  grpc-open-tel:
      image: grpc-open-tel:latest
      build: .
      ports:
          - "5167:80"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
        - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831